apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-x-deployment
spec:
  replicas: 8
  selector:
    matchLabels:
      app: helloworld-x
  template:
    metadata:
      labels:
        app: helloworld-x
    spec:
      containers:
      - name: k8s-demo
        image: wardviaene/k8s-demo
        ports:
        - name: nodejs-port
          containerPort: 3000
